config/routes.rb
Rails.application.routes.draw do
  root to: 'show#index'
  get 'get_data/index'
  get 'comments/:id', to: 'show#comments',:as => "comments"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id            :integer          not null, primary key
#  post_id       :integer
#  name          :string
#  email         :string
#  body          :text
#  external_uuid :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id            :integer          not null, primary key
#  name          :string
#  external_uuid :integer
#  body          :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  username   :string
#  email      :string
#  phone      :string
#  website    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class User < ApplicationRecord
has_one :user_address
has_one :user_company

  def to_s
    self.username
  end
end

app/models/user_address.rb
# == Schema Information
#
# Table name: user_addresses
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  street     :string
#  suite      :string
#  city       :string
#  zipcode    :string
#  geo_lat    :float
#  geo_lng    :float
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class UserAddress < ApplicationRecord
belongs_to :user
end

app/models/user_company.rb
# == Schema Information
#
# Table name: user_companies
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  name         :string
#  catch_phrase :string
#  bs           :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class UserCompany < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/get_data_controller.rb
class GetDataController < ApplicationController
  def index
     get_users = GetData::GetDataFromUrlService.call({url: "https://jsonplaceholder.typicode.com/users"})
     get_posts = GetData::GetDataFromUrlService.call({url: "https://jsonplaceholder.typicode.com/posts"})
     get_comments = GetData::GetDataFromUrlService.call({url: "https://jsonplaceholder.typicode.com/comments"})
     if [get_users[:status], get_posts[:status], get_comments[:status]].exclude? "400"
       import_users = GetData::CreateUsersService.call({:users_data=>get_users[:response]})
       imports_posts = GetData::CreatePostsService.call({:posts_data=>get_posts[:response]})
       imports_comments = GetData::CreateCommentsService.call({:comments_data=>get_comments[:response]})
     end
  end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
  def index
    @get_data = ShowPostsService.call()
    respond_to do |format|
      format.html
      format.json { render json: @get_data, each_serializer: PostSerializer }
    end
  end

  def comments
    @comments = GetCommentsService.call(params_comments)
  end


  private
  def params_comments
    params.require(:id)
    params.permit(:id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/get_data_helper.rb
module GetDataHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/get_data/index.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center Imported
    =link_to "Return", root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : 'Typicode'
    %meta{ name: "description", content: 'Props from mayka' }
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    %main
      .container
        = yield

app/views/show/_post_table.haml
%table.table.table-striped
  %tbody
    - posts.each_with_index do |post, i|
      %tr
        %td= i + 1
        %td
          %h4= post.name
        %td
          %p= post.body
        %td= post.user
        %td= link_to "show comments", comments_path(post.id)

app/views/show/comments.haml
%h1 Comments
%table.table.table-striped
  - @comments.each_with_index do |comment,i|
    %tr
      %td
        %p= i + 1
      %td
        %h4= comment.name
      %td= comment.email
      %td= comment.body

app/views/show/index.haml
.row
  .col-md-8.col-md-offset-2.col-lg-8.col-lg-offset-2
    %h1.text-center POSTS
    -if @get_data.any?
      = render 'post_table', posts: @get_data
    -else
      =link_to "download data", get_data_index_path